name: lf-sample-repository-api-java

on:
  push:
    branches: [ "1.x" ]
  pull_request:
    branches: [ "1.x" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Current directory  
      run: cd target && echo "`ls -l` and `pwd`"
      
    - name: Run with Maven
      run: cd target && java -cp HelloWorld-1.0-SNAPSHOT.jar HelloWorld
